version: "3.8"

services:
  backend:
    build:
      context: ./services/backend
    container_name: backend
    volumes:
      - ./services/backend:/app
    ports:
      - "5487:5487"
    networks:
      - app-network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5487", "--reload"]

  frontend:
    build:
      context: ./services/frontend
    container_name: frontend
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://backend:5487
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "8081"]

networks:
  app-network:
    driver: bridge